fail_fast: true
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: '(scaffold/.*\.yml)'
      - id: detect-private-key
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-xml
      - id: fix-byte-order-marker
  - repo: local
    hooks:
      - id: regenerate-index
        name: Regenerate index
        entry: ./.build_index.py
        files: .*
        language: python
        language_version: python3.9
        pass_filenames: false
